export const REQUESET_GET_RECENT_SONGS = 'REQUESET_GET_RECENT_SONGS'
export const REQUESET_GET_RECENT_SONGS_SUCCESS = 'REQUESET_GET_RECENT_SONGS_SUCCESS'

export const REQUESET_GET_SEARCH_SONGS = 'REQUESET_GET_SEARCH_SONGS'
export const REQUESET_GET_SEARCH_SONGS_SUCCESS = 'REQUESET_GET_SEARCH_SONGS_SUCCESS'
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE'

export const SELECT_DETAIL = 'SELECT_DETAIL'

export const INIT_FAVORITE = 'INIT_FAVORITE'
export const INIT_FAVORITE_SUCCESS = 'INIT_FAVORITE_SUCCESS'
export const SAVE_FAVORITE = 'SAVE_FAVORITE'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'

/* Legacy Actions */
export const INIT_STATE = "INIT_STATE";
export const SEARCH = "SEARCH";
export const BRAND_FILTER = "BRAND_FILTER";
export const SONG_FILTER = "SONG_FILTER";
export const ADD_FAV = "ADD_FAV";
export const DEL_FAV = "DEL_FAV";
export const OPEN_DETAIL = "OPEN_DETAIL";
export const CLOSE_DETAIL = "CLOSE_DETAIL";