export const REQUEST_GET_RECENT_SONGS = 'REQUEST_GET_RECENT_SONGS'
export const REQUEST_GET_RECENT_SONGS_SUCCESS = 'REQUEST_GET_RECENT_SONGS_SUCCESS'

export const REQUEST_GET_SEARCH_SONGS = 'REQUEST_GET_SEARCH_SONGS'
export const REQUEST_GET_SEARCH_SONGS_SUCCESS = 'REQUEST_GET_SEARCH_SONGS_SUCCESS'
export const REQUEST_GET_SEARCH_SONGS_ERROR = 'REQUEST_GET_SEARCH_SONGS_ERROR'
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE'

export const SELECT_DETAIL = 'SELECT_DETAIL'

export const ADD_INBOX_SONG = 'ADD_INBOX_SONG'
export const DELETE_INBOX_SONG = 'DELETE_INBOX_SONG'
