export const INIT_STATE = 'INIT_STATE'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'
export const CHANGE_BRAND = 'CHANGE_BRAND'

export const REQUEST_GET_RECENT_SONGS = 'REQUEST_GET_RECENT_SONGS'
export const REQUEST_GET_RECENT_SONGS_SUCCESS = 'REQUEST_GET_RECENT_SONGS_SUCCESS'
export const REQUEST_GET_RECENT_SONGS_ERROR = 'REQUEST_GET_RECENT_SONGS_ERROR'

export const REQUEST_GET_SEARCH_SONGS = 'REQUEST_GET_SEARCH_SONGS'
export const REQUEST_GET_SEARCH_SONGS_SUCCESS = 'REQUEST_GET_SEARCH_SONGS_SUCCESS'
export const REQUEST_GET_SEARCH_SONGS_ERROR = 'REQUEST_GET_SEARCH_SONGS_ERROR'
export const CHANGE_SEARCH_SEGMENT = 'CHANGE_SEARCH_SEGMENT'

export const REQUEST_GET_YOUTUBE_ID = 'REQUEST_GET_YOUTUBE_ID'
export const REQUEST_GET_YOUTUBE_ID_SUCCESS = 'REQUEST_GET_YOUTUBE_ID_SUCCESS'
export const REQUEST_GET_YOUTUBE_ID_ERROR = 'REQUEST_GET_YOUTUBE_ID_ERROR'

export const ADD_INBOX_SONG = 'ADD_INBOX_SONG'
export const DELETE_INBOX_SONG = 'DELETE_INBOX_SONG'
export const TOGGLE_INBOX_SONG = 'TOGGLE_INBOX_SONG'
